# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_rule_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(618, 526)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.rulename_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.rulename_label.setFont(font)
        self.rulename_label.setObjectName("rulename_label")
        self.gridLayout.addWidget(self.rulename_label, 0, 0, 1, 1)
        self.rulename_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.rulename_lineEdit.setText("")
        self.rulename_lineEdit.setObjectName("rulename_lineEdit")
        self.gridLayout.addWidget(self.rulename_lineEdit, 0, 1, 1, 1)
        self.file_path_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.file_path_label.setFont(font)
        self.file_path_label.setObjectName("file_path_label")
        self.gridLayout.addWidget(self.file_path_label, 1, 0, 1, 1)
        self.file_path_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.file_path_lineEdit.setObjectName("file_path_lineEdit")
        self.gridLayout.addWidget(self.file_path_lineEdit, 1, 1, 1, 1)
        self.folder1_toolButton = QtWidgets.QToolButton(Dialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/文件夹.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.folder1_toolButton.setIcon(icon)
        self.folder1_toolButton.setObjectName("folder1_toolButton")
        self.gridLayout.addWidget(self.folder1_toolButton, 1, 2, 1, 1)
        self.file1_toolButton = QtWidgets.QToolButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../resources/文件.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file1_toolButton.setIcon(icon1)
        self.file1_toolButton.setObjectName("file1_toolButton")
        self.gridLayout.addWidget(self.file1_toolButton, 1, 3, 1, 1)
        self.sync_path_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.sync_path_label.setFont(font)
        self.sync_path_label.setObjectName("sync_path_label")
        self.gridLayout.addWidget(self.sync_path_label, 2, 0, 1, 1)
        self.sync_path_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.sync_path_lineEdit.setObjectName("sync_path_lineEdit")
        self.gridLayout.addWidget(self.sync_path_lineEdit, 2, 1, 1, 1)
        self.folder2_toolButton = QtWidgets.QToolButton(Dialog)
        self.folder2_toolButton.setIcon(icon)
        self.folder2_toolButton.setObjectName("folder2_toolButton")
        self.gridLayout.addWidget(self.folder2_toolButton, 2, 2, 1, 1)
        self.file2_toolButton = QtWidgets.QToolButton(Dialog)
        self.file2_toolButton.setIcon(icon1)
        self.file2_toolButton.setObjectName("file2_toolButton")
        self.gridLayout.addWidget(self.file2_toolButton, 2, 3, 1, 1)
        self.file_treeView = QtWidgets.QTreeView(Dialog)
        self.file_treeView.setObjectName("file_treeView")
        self.gridLayout.addWidget(self.file_treeView, 3, 0, 1, 4)
        self.sync_treeView = QtWidgets.QTreeView(Dialog)
        self.sync_treeView.setObjectName("sync_treeView")
        self.gridLayout.addWidget(self.sync_treeView, 4, 0, 1, 4)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "新增规则"))
        self.rulename_label.setText(_translate("Dialog", "规则名称"))
        self.file_path_label.setText(_translate("Dialog", "原文件路径"))
        self.folder1_toolButton.setText(_translate("Dialog", "..."))
        self.file1_toolButton.setText(_translate("Dialog", "..."))
        self.sync_path_label.setText(_translate("Dialog", "同步路径"))
        self.folder2_toolButton.setText(_translate("Dialog", "..."))
        self.file2_toolButton.setText(_translate("Dialog", "..."))
